### PR TITLE
Cybrics + Readme

### PR DESCRIPTION
**Pull request by Hennich**

### CODE REVIEW

**Review by domenukk — COMMENTED** [review]
Do we really want a general Readme? I fear it will get out of date eventually.

**Comment by gehaxelt** [comment]
I agree with @domenukk on the main readme. Either we make it a policy to also update the readme with every writeup-MR or we drop it.

**Comment by Hennich** [comment]
Then we should add the policy.
It looks much better to have this list and it's not much work. If someone forgets, the next one can still add it and if things get out of hand, this means, we have lots of writeups, so it's something else to be happy about. :)

**Comment by Trolldemorted** [comment]
If you want an up-to-date list of markdown files you could use github pages, which might be better than lumbering a policy on everyone :)

**Comment by domenukk** [comment]
Accepted without Readme for now :)

**Pull request merged**
